#!/bin/bash

# Script to find the base directory of you repositories.
# It ASSUMES that you put this repository into the root of your workspace

set -euf -o pipefail

echo "$(readlink -f "$(dirname "$0")/..")"
